[package]
name = "port-scanner"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.4", features = ["derive", "help", "std", "usage"], default-features = false }
ipnet = { version = "2.8" }